SET(speedcrunch_RESOURCES
resources/speedcrunch.qrc
)

set(speedcrunch_HEADERS
core/anglemode.h
core/book.h
core/complexform.h
core/constants.h
core/colorscheme.h
core/evaluator.h
core/functions.h
core/manualserver.h
core/session.h
core/errors.h
core/numberformatter.h
core/pageserver.h
core/settings.h
core/opcode.h
core/sessionhistory.h
core/sessionjsonkeys.h
core/symbolicnumberformat.h
core/userdefinitions.h
core/variable.h
core/userfunction.h
core/userunit.h
gui/aboutbox.h
gui/bitfieldwidget.h
gui/bookdock.h
gui/constantswidget.h
gui/customkeypaddialog.h
gui/displayformatutils.h
gui/dockcomboboxchevron.h
gui/dockliststyle.h
gui/editor.h
gui/functiontooltiputils.h
gui/functionswidget.h
gui/historywidget.h
gui/genericdock.h
gui/keypad.h
gui/mainwindow.h
gui/manualwindow.h
gui/displayfontdialog.h
gui/numberformatdialog.h
    gui/notationandprecisiondialog.h
gui/oklchutils.h
gui/resultdisplay.h
gui/textmetrics.h
gui/tooltipstyleutils.h
gui/variablelistwidget.h
gui/userfunctionlistwidget.h
gui/userunitlistwidget.h
gui/syntaxhighlighter.h
gui/themedlineedit.h
gui/uiconfig.h
gui/versioncheck.h
math/floatnum/floatcommon.h
math/floatnum/floatconfig.h
math/floatnum/floatconst.h
math/floatnum/floatconvert.h
math/floatnum/floaterf.h
math/floatnum/floatexp.h
math/floatnum/floatgamma.h
math/floatnum/floathmath.h
math/floatnum/floatincgamma.h
math/floatnum/floatio.h
math/floatnum/floatipower.h
math/floatnum/floatlog.h
math/floatnum/floatlogic.h
math/floatnum/floatlong.h
math/floatnum/floatnum.h
math/floatnum/floatpower.h
math/floatnum/floatseries.h
math/floatnum/floattrig.h
math/hmath.h
math/number.h
math/rational.h
math/quantity.h
core/units.h
core/unitdisplayformat.h
)

set(speedcrunch_SOURCES
main.cpp
core/book.cpp
core/constants.cpp
core/colorscheme.cpp
core/evaluator.cpp
core/functions.cpp
core/mathdsl.cpp
core/manualserver.cpp
core/numberformatter.cpp
core/pageserver.cpp
core/settings.cpp
core/session.cpp
core/sessionhistory.cpp
core/userdefinitions.cpp
core/variable.cpp
core/userfunction.cpp
core/userunit.cpp
core/opcode.cpp
gui/aboutbox.cpp
gui/bitfieldwidget.cpp
gui/bookdock.cpp
gui/constantswidget.cpp
gui/customkeypaddialog.cpp
gui/displayformatutils.cpp
gui/dockcomboboxchevron.cpp
gui/dockliststyle.cpp
gui/editor.cpp
gui/functiontooltiputils.cpp
gui/functionswidget.cpp
gui/historywidget.cpp
# added here explicitly so it shows up in QtCreator
gui/genericdock.h
gui/keypad.cpp
gui/mainwindow.cpp
gui/manualwindow.cpp
gui/displayfontdialog.cpp
gui/numberformatdialog.cpp
gui/notationandprecisiondialog.cpp
gui/oklchutils.cpp
gui/resultdisplay.cpp
gui/splittertreeutils.cpp
gui/syntaxhighlighter.cpp
gui/themedlineedit.cpp
gui/tooltipstyleutils.cpp
gui/variablelistwidget.cpp
gui/userfunctionlistwidget.cpp
gui/userunitlistwidget.cpp
gui/versioncheck.cpp
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/floatnum/floatincgamma.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
)

set(testhmath_SOURCES
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/rational.cpp
math/quantity.cpp
math/cmath.cpp
core/units.cpp
core/unitdisplayformat.cpp
math/cnumberparser.cpp
tests/testhmath.cpp
)

set(testevaluator_HEADERS
core/evaluator.h
core/functions.h
gui/resultdisplay.h
gui/syntaxhighlighter.h
gui/uiconfig.h
)

set(testevaluator_SOURCES
core/constants.cpp
core/colorscheme.cpp
core/evaluator.cpp
core/functions.cpp
core/mathdsl.cpp
core/settings.cpp
core/userfunction.cpp
core/userunit.cpp
core/session.cpp
core/sessionhistory.cpp
core/variable.cpp
core/numberformatter.cpp
gui/displayformatutils.cpp
gui/dockliststyle.cpp
gui/functiontooltiputils.cpp
gui/oklchutils.cpp
gui/resultdisplay.cpp
gui/splittertreeutils.cpp
gui/syntaxhighlighter.cpp
gui/tooltipstyleutils.cpp
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
tests/testevaluator.cpp
)

set(testfloatnum_SOURCES
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/number.c
tests/testfloatnum.c
)

set(testcmath_SOURCES
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
tests/testcmath.cpp
)

set(testdmath_SOURCES
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
tests/testdmath.cpp
)

set(testeditorui_SOURCES
core/constants.cpp
core/colorscheme.cpp
core/evaluator.cpp
core/functions.cpp
core/mathdsl.cpp
core/settings.cpp
core/userfunction.cpp
core/userunit.cpp
core/session.cpp
core/sessionhistory.cpp
core/variable.cpp
core/numberformatter.cpp
gui/displayformatutils.cpp
gui/functiontooltiputils.cpp
gui/oklchutils.cpp
gui/resultdisplay.cpp
gui/syntaxhighlighter.cpp
gui/editor.cpp
gui/tooltipstyleutils.cpp
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
tests/testeditorui.cpp
)

set(testoklch_SOURCES
gui/oklchutils.cpp
tests/testoklch.cpp
)

set(testdocksui_SOURCES
core/constants.cpp
core/colorscheme.cpp
core/evaluator.cpp
core/functions.cpp
core/mathdsl.cpp
core/settings.cpp
core/userfunction.cpp
core/userunit.cpp
core/session.cpp
core/sessionhistory.cpp
core/variable.cpp
core/numberformatter.cpp
gui/displayformatutils.cpp
gui/constantswidget.cpp
gui/dockliststyle.cpp
gui/functiontooltiputils.cpp
gui/oklchutils.cpp
gui/resultdisplay.cpp
gui/splittertreeutils.cpp
gui/syntaxhighlighter.cpp
gui/editor.cpp
gui/themedlineedit.cpp
gui/tooltipstyleutils.cpp
gui/variablelistwidget.cpp
gui/userunitlistwidget.cpp
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
tests/testdocksui.cpp
)

set(testdisplayui_SOURCES
core/book.cpp
core/constants.cpp
core/colorscheme.cpp
core/evaluator.cpp
core/functions.cpp
core/manualserver.cpp
core/mathdsl.cpp
core/pageserver.cpp
core/settings.cpp
core/userfunction.cpp
core/userunit.cpp
core/userdefinitions.cpp
core/session.cpp
core/sessionhistory.cpp
core/variable.cpp
core/numberformatter.cpp
gui/aboutbox.cpp
gui/bitfieldwidget.cpp
gui/bookdock.cpp
gui/constantswidget.cpp
gui/customkeypaddialog.cpp
gui/displayformatutils.cpp
gui/dockliststyle.cpp
gui/functiontooltiputils.cpp
gui/functionswidget.cpp
gui/historywidget.cpp
gui/keypad.cpp
gui/dockcomboboxchevron.cpp
gui/mainwindow.cpp
gui/manualwindow.cpp
gui/displayfontdialog.cpp
gui/numberformatdialog.cpp
gui/notationandprecisiondialog.cpp
gui/oklchutils.cpp
gui/resultdisplay.cpp
gui/splittertreeutils.cpp
gui/syntaxhighlighter.cpp
gui/editor.cpp
gui/themedlineedit.cpp
gui/tooltipstyleutils.cpp
gui/userfunctionlistwidget.cpp
gui/variablelistwidget.cpp
gui/userunitlistwidget.cpp
gui/versioncheck.cpp
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
resources/speedcrunch.qrc
tests/testdisplayui.cpp
)

set(testserial_SOURCES
core/numberformatter.cpp
core/settings.cpp
math/floatnum/floatcommon.c
math/floatnum/floatconst.c
math/floatnum/floatconvert.c
math/floatnum/floaterf.c
math/floatnum/floatexp.c
math/floatnum/floatgamma.c
math/floatnum/floathmath.c
math/floatnum/floatio.c
math/floatnum/floatipower.c
math/floatnum/floatlog.c
math/floatnum/floatlogic.c
math/floatnum/floatlong.c
math/floatnum/floatnum.c
math/floatnum/floatpower.c
math/floatnum/floatseries.c
math/floatnum/floattrig.c
math/hmath.cpp
math/number.c
math/cmath.cpp
math/cnumberparser.cpp
math/rational.cpp
math/quantity.cpp
core/units.cpp
core/unitdisplayformat.cpp
tests/testserial.cpp
)
